version: '3.3'

services:
  loja-abc:
    build: ./  
    ports:
      - 9082:80
    volumes:
      - ./:/usr/share/nginx/html
    restart: always
    depends_on:
      - db #sobe primeiro o sql pra depois esse serviço
    networks:
      - dockernetworks #nome da rede
  
  db:
    image: mysql
    restart: always
    ports: 
      - 3308:3306 #para acessar da minha maquina
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - .docker/dbdata:/var/lib/mysql # ou seja tudo que tem dentro da /var/lib/mysql onde guarda toda info vai para minha pasta que criei docker/dbdata
    networks:
      - dockernetworks

  db-testing:
    image: mysql
    restart: always
    ports: 
      - 3309:3306 #para acessar da minha maquina
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: testing
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    networks:
      - dockernetworks

networks:
  dockernetworks:
    driver: bridge
